### PR TITLE
Correct FOV e ZCombatInterface rendering

### PR DESCRIPTION
**Pull request by grandao**
Hi,
These changes fixes the vertical FOV and the in game interface rendering aspect.

### CODE REVIEW

**Comment by Asunaya** [comment]
The effect this applies to the camera is already accomplished by the /camfix command (although it's not *quite* the same effect).

The effect this applies to the ingame interface -- stuffing it into a 4:3 region in the middle of the screen -- looks terrible to me. Do people actually prefer that to it being stretched? :o

**Comment by grandao** [comment]
Didn't noticed the camfix command.
About the 4:3 rendering I personally think it looks better at least in a 34" 21:9 monitor. In these ultrawide monitors the stretching is large and usually your focus is in the middle of the screen, to see the interface in the border you have to actually turn your head.
That is my personal opinion, if you think it doesn't feel right you can drop this PR.

**Comment by grandao** [comment]
I'm closing the PR as even if you would accept the Interface fix change it doesn't work properly without the FOV commit.

**Comment by Asunaya** [comment]
> Didn't noticed the camfix command.

Yeah, it should really be in the options so it's easier to notice and use. I haven't really added much to the options because editing interface XMLs is so tenuous. :/ I'm going to have to make something for viewing interface stuff without having to perpetually restart the game sometime.

Anyway, changing the FOV in that way seems like a better way to do the camfix thing, so it could be changed to that. It should definitely be optional though. FGunz added something similar as an unconditional thing in an update once and people didn't like it *at all*. XD

> About the 4:3 rendering I personally think it looks better at least in a 34" 21:9 monitor. In these ultrawide monitors the stretching is large and usually your focus is in the middle of the screen, to see the interface in the border you have to actually turn your head.

Okay. :o Maybe add it as an option? If the default FOV doesn't work for the ZScreenEffect stuff, you could just change the projection matrix before you draw them, and then change it back afterwards.

**Comment by grandao** [comment]
> Anyway, changing the FOV in that way seems like a better way to do the camfix thing, so it could be changed to that. It should definitely be optional though.
Both approaches are equivalent visually but I think logically changing the FOV is the corret fix, Yet the camfix is much more clean and manageable thus I prefer to keep the camfix code.

> Okay. :o Maybe add it as an option?
I'll work on the  4:3 inteface fix as an option on top of camfix.

**Comment by grandao** [comment]
Please disregard the above text. The approaches are not equivalente, I just figured it out. Next time I should do the math before typing.
That's why people complained about it in Fgunz changing camera distance is not equal changing FOV.
If you think it is not necessary to make this fix toggleable (like camfix) you can reopen it.

Following is the graphic comparison. (There is a slight diferrence from reference 4:3 to fixed FOV 21:9 because I had to restart the game and I'm slight shifted in position).
Reference 4:3
Reference 4:3

Corrected FOV 21:9
Corrected FOV 21:9

Camfix 21:9
Camfix 21:9

Default 21:9
Default 21:9

**Comment by Asunaya** [comment]
Never actually played on 21:9; I never realized the camfix thing looked that different and that the stretching got so bad. :O I can see what you mean now. Still think they should be optional, but they should definitely be added.

**Comment by Asunaya** [comment]
I've tried adding the features as /camfix and /interfacefix in 5ac50df and f2f549a, respectively. Haven't added saving to config.xml yet so the options don't persist, but do they seem ok otherwise? :o

**Pull request closed without merging**
